### ISSUE TITLE
Создать (описать) начальную структуру проекта

### ISSUE THREAD

**Issue by seralekseenko** [vpodgurskiy/textAnalyzer#1]
План:
1) Изучить требования в ТЗ. Разложить для себя составляющие приложения исходя из ТЗ. 
2) Продумать структуру классов. Это может быть согласно [MVC](https://ru.wikipedia.org/wiki/Model-View-Controller), а может свои какие-то наработки. В любом случае это стоит делать с учетом п. 3.
3) Максимально разнести по разным классам точки ввода/вывода, разные библиотеки обработки строк, классы хранящие какие-либо данные. Это необходимо:

         -  для удобной замены тех или иных библиотек в процессе разработки
         -  для возможности портирования приложения в облачные технологии
         -  для применения (возможно) графического интерфейса к этому приложению

Продуманная структура проекта должна быть как конструктор Лего.

**Comment by vpodgurskiy** [comment]
Не придумал методы для исходящего потока, т.е. сохранение или просто преобразованный текст.

**Comment by vpodgurskiy** [comment]
Схема получилась следующая: 
1. Получаем входящую строку, которую ввел пользователь.
2. Парим ее, выделяем где параметры, где сам текст или файл т.п.
3. Отправляем часть в который текст или файл, у меня это аргумент, на извлечение этого текста.
4. Полученный текст отправляем на преобразование, подсчет слов и т.п.
5. Преобразованный текст сохраняем, или выводим или еще что то с ним делаем.
конец)

**Comment by seralekseenko** [comment]
Согласен с описанной схемой в предыдущем комментарии.
Но в общем пока считаю issue не закрытым.

**Comment by seralekseenko** [comment]
Круть.
Не знаю как закрыть issue )
