### ISSUE TITLE
Протестировать Travis

### ISSUE THREAD

**Issue by seralekseenko** [vpodgurskiy/textAnalyzer#2]
Создать тестовый класс и создать к нему ЮНИТ-тесты. И запустить Тревисом эти тесты.

**Comment by vpodgurskiy** [comment]
чтобы запускались тесты через travis нужно было в pom.xml добавить блок с расположением тестов `<build>
        <directory>target</directory>
        <outputDirectory>target/classes</outputDirectory>
        <testOutputDirectory>target/test-classes</testOutputDirectory>
        <testSourceDirectory>tst</testSourceDirectory>
    </build>`. По умолчанию тесты запускаются без подсветки (mvn test -B), если хотим с подсветкой, нужно прописывать в travis.yml `script: mvn test`

**Comment by seralekseenko** [comment]
Не пойму как код проходит тесты, когда в нем ошибка....

**Comment by vpodgurskiy** [comment]
Видимо надо еще линтер подключить к travis.
